language: python
python:
  - 3.6
# command to install dependencies
install:
  - pip install codecov
  - pip install -r requirements.txt
# command to run the dependencies
script:
  - pytest --cov=looter --cov-config .coveragerc

after_success:
  - codecov

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist build
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
    repo: alphardex/looter
    python: 3.6